[package]
name = "gracilaria"
version = "0.1.0"
edition = "2024"

[dependencies]
atools = "0.1.7"
dsb = { version = "0.1.0", path = "../dsb" }
fimg = { path = "../fimg" }
implicit-fn = "0.1.0"
ropey = "1.6.1"
softbuffer = "0.4.6"
swash = "0.2.5"
winit = "0.30.12"

tree-sitter = "0.25.0"
tree-sitter-rust = "0.24"
tree-sitter-highlight = "0.25.0"
car = "0.1.2"
memchr = "2.7.5"
lower = "0.2.0"
amap = "0.1.2"

[build-dependencies]
cc = "*"

[profile.release]
debug = 2
overflow-checks = true
debug-assertions = true
