[package]
name = "gracilaria"
version = "0.1.0"
edition = "2024"

[dependencies]
dsb = { git = "https://github.com/bend-n/dsb" }
fimg = { git = "https://github.com/bend-n/fimg" }
pattypan = { git = "https://github.com/bend-n/pattypan" }
implicit-fn = "0.1.0"
ropey = "1.6.1"
softbuffer = "0.4.6"
swash = "0.2.5"
winit = "0.30.12"

tree-sitter = "0.25.0"
car = "0.1.2"
memchr = "2.7.5"
lower = "0.2.0"
amap = "0.1.4"
run_times = "0.1.0"
array_chunks = "1.0.0"
rust-fsm = { git = "https://github.com/bend-n/rust-fsm", features = [
    "diagram",
] }
clipp = "0.1.0"
diff-match-patch-rs = "0.5.1"
regex = "1.11.3"
tree-house = { version = "0.3.0", features = ["fixtures"] }

# for tree house grammar loading
helix-loader = { git = "https://github.com/bend-n/helix" }
helix-core = { git = "https://github.com/bend-n/helix" }

lsp-types = { git = "https://github.com/bend-n/helix", package = "helix-lsp-types", features = [
    "proposed",
] }

lsp-server = { git = "https://github.com/bend-n/rust-analyzer" }
rust-analyzer = { git = "https://github.com/bend-n/rust-analyzer" }

serde_json = "1.0.145"
serde = "1.0.228"
serde_derive = "1.0.228"
log = "0.4.28"
crossbeam = { version = "0.8.4", features = ["nightly", "crossbeam-channel"] }
test-log = "0.2.18"
env_logger = "0.11.8"
url = "2.5.7"
anyhow = "1.0.100"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "sync"] }
regex-cursor = "0.1.5"
papaya = "0.2.3"
markdown = "1.0.0"
itertools = "0.14.0"
pin-project = "1.1.10"
replace_with = "0.1.8"
nucleo = "0.5.0"
tokio-util = { version = "0.7.17", features = ["rt"] }
scopeguard = "1.2.0"
arc-swap = "1.7.1"
atools = "0.1.10"
swizzle = "0.1.0"
walkdir = "2.5.0"
niri = { package = "niri-ipc", version = "25.11.0" }
libc = "0.2.180"
serde_bencode = "0.2.4"
rustc-hash = "=2.1.1"
serde_bencoded = "0.3.2"

[profile.dev.package]
rust-analyzer.opt-level = 3
fimg.opt-level = 3
nucleo.opt-level = 3
tree-house.debug-assertions = false

[profile.release.package.tree-house]
debug-assertions = false

[profile.release.package]
fimg.debug-assertions = true

[profile.release]
debug = 2
overflow-checks = true
debug-assertions = true

[profile.dev]
incremental = false
